version: '3.1'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - ./mongo/db:/data/db
  back:
    build: .
    container_name: back
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mongo
      DB_PORT: "27017"
      DB_LOGIN: mongo
      DB_PASSWORD: mongo
    links:
      - mongo